### ISSUE TITLE
Add USB to Serial Stack

### ISSUE THREAD

**Issue by MrKevinWeiss** [MrKevinWeiss/Testing#9]
I think I would like to add USB support to the BPT.  This would remove the requirement for wiring up a external usb to serial converter making it easier for people to adapt.  This would require a change in pinout.

Changes:
- SPI2 (PB12-PB15) -> SPI1 (PB3-PB5 & PA15) this means no jtag interface but since it uses swd it should be fine
- UART1 (PA9-PA12) -> UART3 (PB11, PB10, PB13, PB14)
- +USB (PA11, PA12)
- -UART2 (PA2,PA3)

To think about:
- Interrupt priority issues with USB
- Overhead in complexity, cpu usage and code size
- Opens up two more timers (PA9, PA10)
- Would we need to get a USB Vendor licence
- Customization of usb name (so it can be easily identified)

**Comment by smlng** [comment]
Please consider the following:

- USART1 can be used for flashing, will this still be possible with these changes?
- can we have both? Serial via UART with wires AND using USB, that would be very convenient.

Otherwise, yes USB would ease deployment.

**Comment by MrKevinWeiss** [comment]
Currently USART1 is used as the DUT test, this would free up the RX and TX of USART1 (but one could just unplug from the DUT if they want to use the ROM bootloader).  I think using the ROM bootloader would be achievable regardless (as long as the modem support isn't used for it).

Yes we can have both but I don't know why, every use can seems like it can have USB (RPi or computer) I don't think an MCU should have access to the config registers.  This would also add some complexity in terms of concurrency.  I would prefer to see the UART interface tot he config registers gone and only done through USB.

My worry is the interrupt priority, with the UART the priority is low but with the USB it may need to be higher so things don't timeout, if that is the case it may effect jitter and timings of things during the test.  The only thing that would calm that fear is that only one thing should communicate at a time.  maybe a keep alive signal might cause some issues but I am not too sure about the USB protocol and what is handled by the hardware.

An example of what I am talking about is the i2c clk stretch delay test, this stays in the interrupt for up to 16ms I think, if it is blocking USB signal then it may be a problem.  On the other hand if the USB is higher priority then when the I2C recognizes the address it may not be able to load in the data if it is stuck waiting for the USB to finish (which could either cause an unwanted clk stretch or sending incorrect data is clk stretch is disabled).

Maybe I am overthinking it though and just need to try it out.

**Comment by MrKevinWeiss** [comment]
Seems to be functional just has some bugs that will be listed in other issues.
